# Generated by Django 5.0.4 on 2024-07-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(related_name='custom_users', to='accounts.role'),
        ),
    ]
